Repository containers/podman-machine-os, pull requests merged in 2025-02, with the labels that each got.

#76 fix broken exit code checks in rpm-ostree install
  podman-image/Containerfile
  verify/basic_test.go
Labels: approved, lgtm, release-note-none

#77 [v5.4] fix broken podman version
  podman-image/Containerfile
  podman-rpm-info-vars.sh
  verify/basic_test.go
Labels: approved, lgtm, release-note

#78 replace randomString func fromcontainers/storage
  verify/config_test.go
  verify/go.mod
  verify/go.sum
  verify/vendor/github.com/containers/storage/AUTHORS
  verify/vendor/github.com/containers/storage/LICENSE
  verify/vendor/github.com/containers/storage/NOTICE
  verify/vendor/github.com/containers/storage/pkg/regexp/regexp.go
  verify/vendor/github.com/containers/storage/pkg/regexp/regexp_dontprecompile.go
  verify/vendor/github.com/containers/storage/pkg/regexp/regexp_precompile.go
  verify/vendor/github.com/containers/storage/pkg/stringid/README.md
  verify/vendor/github.com/containers/storage/pkg/stringid/stringid.go
  verify/vendor/modules.txt
Labels: approved, lgtm, release-note-none

#85 podman v5.4.0
  .cirrus.yml
  podman-image/99-podman-sshd.conf
  podman-rpm-info-vars.sh
Labels: approved, do-not-merge/hold, lgtm, release-note

#64 Release RPM: Fetch from Podman upstream PR
  build.sh
  podman-image/Containerfile
  podman-rpm-info-vars.sh
Labels: approved, lgtm, release-note
